#!/bin/bash
FILE=$1
MESSAGE=$(cat "$FILE")

if [[ "$MESSAGE" == "fixup!"* ]]; then
    exit 0
fi

TICKET=$(git rev-parse --abbrev-ref HEAD | grep -Eo '(\w+/)?(\w+[-_])?[0-9]+' | grep -Eo '(\w+[-])?[0-9]+$' | tr "[:lower:]" "[:upper:]" | tail -n1)

if [[ $TICKET == "" || $(head -n 1 "$FILE") == "$TICKET "* ]]; then
    exit 0
fi

{
    echo "$TICKET "
    echo "$MESSAGE"
} >"$FILE"
