#!/usr/bin/env bash
set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive

DOTBOT_VER="$(
    git -C "${DOTBOT_DIR}" name-rev --tags --name-only \
        "$(git -C "${DOTBOT_DIR}" rev-parse HEAD)"
)"
echo "Using dotbot version: ${DOTBOT_VER}"

for pyver in 3.13 3.12 3.11 3.10 3.9 3.8 3.7 3; do
    if command -v python${pyver} >/dev/null; then
        PYTHON_BIN="python${pyver}"
        echo "Using python version: ${pyver}"
        break
    fi
done

if [ -z "${PYTHON_BIN}" ]; then
    echo "No supported python version found"
    exit 1
fi

exec "$PYTHON_BIN" "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
    -d "${BASEDIR}" \
    -c "${CONFIG}" \
    "${@}"
