#!/bin/bash

# Copyright (c) 2013-2015 Artem Shinkarov <artyom.shinkaroff@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

set -e

script_name=$(basename $0)
params=$(getopt \
         -o vnbdI:up:eflh \
         -l version,nofork,beep,dpms,inactivity-timeout:,no-unlock-indicator,pointer:,ignore-empty-password,show-failed-attempts,logo,help \
         -n "$script_name" -- "$@")
eval set -- "$params"
# exit on bad arguments
if [ $? -ne 0 ]; then
    exit 1
fi

usage () {
    cat <<EOF
A wrapper around i3lock that sets a blurred screenshot 
as a background image for the screen saver.

Usage: $script_name [options]

    -v, --version               version of the i3lock.
    -n, --nofork                don't fork i3lock after start.
    -b, --beep                  enable beeping.
    -d, --dpms                  enable turning off the screen with DPMS.
    -I sec,
    --inactivity-timeout=sec    specifies  the  number of seconds i3lock will 
                                wait for another password before turning
                                off the monitors.
    -u, --no-unlock-indicator   disable the unlock indicator.
    -p win|default, 
    --pointer=win|default       do not hide the mouse pointer on default
                                or the current position of the mouse pointer.
    -e, --ignore-empty-password when an empty password is provided by the user,
                                do  not  validate  it.

    Please note, that all the options are being passed directly to i3lock.
    See "man i3lock" for more details.
EOF
}

arg_test () { 
    # Filter out arguments that are invalid
    while true; do
       case "$1" in
           -v|--version)
               i3lock -v
               exit
               ;;
           -n|--nofork)                
               shift;;
           -b|--beep)              
               shift;;
           -d|--dpms)                  
               shift;;
           -I|--inactivity-timeout)
               shift
               case "$1" in
                   [0-9]*)
                       shift;;
                    *)
                       echo "$script_name: invalid option \"$1\" for argument -I" \
                            "number expected" >&2
                       exit 1
                       ;;
               esac
               ;;
           -u|--no-unlock-indicator)   
               shift;;
           -p|--pointer) 
               shift
               case "$1" in
                   win|default)
                       shift;;
                   *)
                       echo "$script_name: invalid option \"$1\" for argument -p" >&2
                       exit 1
                       ;;
               esac
               ;;
           -e|--ignore-empty-password)
               shift;;
           -f|--show-failed-attempts)
               shift;;
           -h|--help)
               usage
               exit
               ;;
           --)
               shift 
               break ;;

           *)
               echo "$script_name: invalid argument \"$1\"" >&2
               exit 1
               ;;
       esac
    done

    if [ $# -ne 0 ]; then
       echo "$script_name: invalid arguments \"$@\""
       exit 1
    fi
}


arg_test $@

file1=$(mktemp --tmpdir i3lock-wrapper-XXXXXXXXXX.png)
file2=$(mktemp --tmpdir i3lock-wrapper-XXXXXXXXXX.png)

scrot -z -d0 "$file1"
convert "$file1" -blur 0x8 -colorspace gray "$file2"
rm "$file1" # Remove for security

if [ $use_logo -eq 1 ]; then
    superimpose_padlock
fi

cmd=()
for i in $@; do
    if [[ $i != '-l'  &&  $i != '--logo' && $i != '--' ]]; then
        cmd+="$i "
    fi
done

# drop the last "--" introduced by getopt
i3lock -d -e -i "$file2" ${cmd}

trap "rm '$file2'" EXIT
