# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill \
$python\
$line_break\
$status\
$character\
"""

[directory]
truncate_to_repo = true
style = 'fg:39'
before_repo_root_style = 'dimmed fg:39'
repo_root_style = 'bold fg:39'

[git_branch]
format ='[$branch(:$remote_branch)]($style) '
style = 'fg:225'
truncation_length = 42

[git_status]
format = '([$stashed$conflicted$modified$ahead_behind]($style))'
style = 'fg:225'
conflicted = '=${count} '
ahead = '⇡${count} '
diverged = '⇡${ahead_count} ⇣${behind_count} '
behind = '⇣${count} '
stashed = '*${count} '
modified = '~${count} '

[python]
format = '([${symbol}$virtualenv]($style) )'
symbol = ' '
style = '   fg:bright-green'

[time]
format = '[$time]($style)'
style = 'dimmed'
disabled = false
