# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$golang\
$nodejs\
$rust\
$vagrant\
$env_var\
$custom\
$sudo\
$fill \
$cmd_duration\
$jobs\
$python\
$kubernetes\
$time\
$line_break\
$status\
$os\
$container\
$shell\
$character\
"""

[shell]
disabled = false
fish_indicator = ''

[username]
format = '[$user]($style)'
style_user = 'fg:183'

[hostname]
format = '[@$hostname]($style) '
style = 'fg:183'
[directory]
truncate_to_repo = false
style = 'fg:39'
before_repo_root_style = 'dimmed fg:39'
repo_root_style = 'bold fg:39'

[git_branch]
format ='[$branch(:$remote_branch)]($style) '
style = 'fg:225'
truncation_length = 42

[git_status]
format = '([$stashed$conflicted$modified$ahead_behind]($style))'
style = 'fg:225'
conflicted = '=${count} '
ahead = '⇡${count} '
diverged = '⇡${ahead_count} ⇣${behind_count} '
behind = '⇣${count} '
stashed = '*${count} '
modified = '~${count} '

[kubernetes]
format = '([$symbol$context/$namespace]($style) )'
symbol = '⎈ '
style = 'fg:bright-blue'
disabled = false

[jobs]
symbol = ''

[python]
format = '([${symbol}$virtualenv]($style) )'
symbol = ' '
style = '   fg:bright-green'

[time]
format = '[$time]($style)'
style = 'dimmed'
disabled = false

[cmd_duration]
format = '[$duration]($style) '
min_time = 5_000
style = 'dimmed'
